In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
data = pd.read_csv(r"C:\Users\loneo\OneDrive\Documents\ev-charging-demand-segmentation\data\raw\EVChargingStationUsage.csv")

C:\Users\loneo\AppData\Local\Temp\ipykernel_3716\3935048766.py:1: DtypeWarning: Columns (0: User ID, 1: County, 2: Model Number) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r"C:\Users\loneo\OneDrive\Documents\ev-charging-demand-segmentation\data\raw\EVChargingStationUsage.csv")

In [54]:
df = data.copy()

In [55]:
cols = [
    'Start Date',
    'End Date',
    'Transaction Date (Pacific Time)',
    'Total Duration (hh:mm:ss)',
    'Charging Time (hh:mm:ss)'
]

for col in cols:
    count = df[col].astype(str).str.match(r'^\d+(\.\d+)?$', na=False).sum()
    print(f"{col}: {count}")

Start Date: 0
End Date: 40
Transaction Date (Pacific Time): 40
Total Duration (hh:mm:ss): 0
Charging Time (hh:mm:ss): 0

In [56]:
mask = df['Transaction Date (Pacific Time)'].astype(str).str.match(r'^\d+(\.\d+)?$', na=False)

df.loc[mask, 'Transaction Date (Pacific Time)'] = pd.to_datetime(pd.to_numeric(df.loc[mask, 'Transaction Date (Pacific Time)']),unit='D',origin='1899-12-30').dt.strftime('%m/%d/%Y %H:%M')

df['Transaction Date (Pacific Time)'] = pd.to_datetime(df['Transaction Date (Pacific Time)'])

In [57]:


mask = df['End Date'].astype(str).str.match(r'^\d+(\.\d+)?$', na=False)

df.loc[mask, 'End Date'] = pd.to_datetime(pd.to_numeric(df.loc[mask, 'End Date']),unit='D', origin='1899-12-30').dt.strftime('%m/%d/%Y %H:%M')

In [58]:
df['End Date'] = pd.to_datetime(df['End Date'])

In [59]:
df['Start Date'] = pd.to_datetime(df['Start Date'])
df['End Date'] = pd.to_datetime(df['End Date'])
df['Transaction Date (Pacific Time)'] = pd.to_datetime(df['Transaction Date (Pacific Time)'])

df['Total Duration (hh:mm:ss)'] = pd.to_timedelta(df['Total Duration (hh:mm:ss)'])
df['Charging Time (hh:mm:ss)'] = pd.to_timedelta(df['Charging Time (hh:mm:ss)'])

In [60]:
print(df[['Start Date','End Date','Transaction Date (Pacific Time)','Total Duration (hh:mm:ss)','Charging Time (hh:mm:ss)']].dtypes)

Start Date                          datetime64[us]
End Date                            datetime64[us]
Transaction Date (Pacific Time)     datetime64[us]
Total Duration (hh:mm:ss)          timedelta64[us]
Charging Time (hh:mm:ss)           timedelta64[us]
dtype: object

In [61]:
df=df.drop_duplicates()

In [65]:
df['Station Name'].value_counts()

Station Name
PALO ALTO CA / HAMILTON #2        23721
PALO ALTO CA / HAMILTON #1        14888
PALO ALTO CA / WEBSTER #1         14432
PALO ALTO CA / BRYANT #2          14388
PALO ALTO CA / HIGH #4            13898
PALO ALTO CA / BRYANT #1          13436
PALO ALTO CA / WEBSTER #2         12669
PALO ALTO CA / CAMBRIDGE #1       11163
PALO ALTO CA / HIGH #1            10756
PALO ALTO CA / WEBSTER #3         10484
PALO ALTO CA / TED THOMPSON #1     9814
PALO ALTO CA / CAMBRIDGE #2        9256
PALO ALTO CA / MPL #6              8995
PALO ALTO CA / HIGH #3             8317
PALO ALTO CA / MPL #4              7787
PALO ALTO CA / MPL #5              7544
PALO ALTO CA / HIGH #2             6929
PALO ALTO CA / RINCONADA LIB 3     6499
PALO ALTO CA / RINCONADA LIB 1     6212
PALO ALTO CA / BRYANT #6           5857
PALO ALTO CA / RINCONADA LIB 2     5553
PALO ALTO CA / BRYANT #5           5331
PALO ALTO CA / CAMBRIDGE #5        4556
PALO ALTO CA / CAMBRIDGE #3        4476
PALO ALTO CA / BRYANT #3           4475
PALO ALTO CA / BRYANT #4           3598
PALO ALTO CA / CAMBRIDGE #4        3428
PALO ALTO CA / TED THOMPSON #3     2455
PALO ALTO CA / TED THOMPSON #4     2226
PALO ALTO CA / TED THOMPSON #2     2217
PALO ALTO CA / MPL #2              1535
PALO ALTO CA / MPL #3              1420
PALO ALTO CA / MPL #1              1044
PALO ALTO CA / BRYANT # 1            13
PALO ALTO CA / SHERMAN 3              8
PALO ALTO CA / SHERMAN 1              7
PALO ALTO CA / SHERMAN 7              4
PALO ALTO CA / SHERMAN 4              4
PALO ALTO CA / SHERMAN 2              4
PALO ALTO CA / SHERMAN 6              3
PALO ALTO CA / SHERMAN 8              2
PALO ALTO CA / SHERMAN 14             2
PALO ALTO CA / SHERMAN 9              1
PALO ALTO CA / SHERMAN 5              1
PALO ALTO CA / SHERMAN 15             1
PALO ALTO CA / SHERMAN 11             1
PALO ALTO CA / SHERMAN 17             1
Name: count, dtype: int64

In [66]:
df.describe()

,Start Date,End Date,Transaction Date (Pacific Time),Total Duration (hh:mm:ss),Charging Time (hh:mm:ss),Energy (kWh),GHG Savings (kg),Gasoline Savings (gallons),Port Number,EVSE ID,Postal Code,Latitude,Longitude,Fee,Plug In Event Id,Driver Postal Code,System S/N
count,259411,259411,259202,259411,259411,259411.000000,259411.000000,259411.000000,259411.000000,1.804640e+05,259411.000000,259411.000000,259411.000000,259411.000000,2.594110e+05,251009.000000,1.804640e+05
mean,2017-06-15 03:21:32.730300,2017-06-15 05:56:35.800948,2017-06-15 01:38:50.115585,0 days 02:29:12.607379,0 days 01:59:56.882464,8.544332,3.588619,1.072313,1.591629,1.462976e+05,94302.315781,37.439565,-122.151264,1.097493,1.188646e+08,94170.304885,1.443790e+11
min,2011-07-29 20:17:00,2011-07-29 23:20:00,2011-07-29 23:20:00,0 days 00:01:00,0 days 00:00:06,0.010000,0.004000,0.001000,1.000000,3.792000e+03,94301.000000,37.422104,-122.163239,0.000000,1.000000e+00,1013.000000,1.023100e+11
25%,2016-04-12 21:31:00,2016-04-13 04:47:00,2016-04-12 18:21:30,0 days 01:10:15,0 days 01:02:24,3.784000,1.589000,0.475000,1.000000,4.358300e+04,94301.000000,37.428318,-122.162170,0.000000,1.573000e+03,94087.000000,1.231100e+11
50%,2017-07-15 11:04:00,2017-07-15 13:21:00,2017-07-14 20:49:30,0 days 02:05:21,0 days 01:48:59,6.868920,2.885000,0.862000,2.000000,1.074270e+05,94301.000000,37.444489,-122.158272,0.000000,3.573000e+03,94304.000000,1.427410e+11
75%,2019-01-25 08:33:30,2019-01-25 11:15:00,2019-01-25 11:47:00,0 days 03:05:24.500000,0 days 02:41:50,11.458754,4.813000,1.438000,2.000000,1.745590e+05,94303.000000,37.446613,-122.145699,1.640000,6.340000e+03,94804.000000,1.705410e+11
max,2020-12-31 18:19:00,2021-01-04 21:01:00,2021-01-04 21:03:00,4 days 18:32:21,0 days 22:55:55,97.360000,40.891000,12.219000,2.000000,5.535441e+06,94306.000000,37.449375,-122.112480,84.560000,1.609436e+09,99354.000000,2.002410e+11
std,NaN,NaN,NaN,0 days 02:12:45.618782,0 days 01:22:57.318305,7.185497,3.017908,0.901780,0.491533,2.429695e+05,1.941666,0.009621,0.015382,1.934419,4.057690e+08,4249.870530,2.483269e+10

In [67]:
df[df['Charging Time (hh:mm:ss)']>df['Total Duration (hh:mm:ss)']].shape

(45, 33)

In [68]:
print(df[df['Station Name']=='PALO ALTO CA / BRYANT #1'].shape)
print(df[df['Station Name']=='PALO ALTO CA / BRYANT # 1'].shape)
print(df['Station Name'].shape)

df['Station Name']=df['Station Name'].replace({'PALO ALTO CA / BRYANT #1':'PALO ALTO CA / BRYANT # 1'})
print(df['Station Name'].shape)

(13436, 33)
(13, 33)
(259411,)
(259411,)

In [69]:
dz=df[df['Charging Time (hh:mm:ss)']>df['Total Duration (hh:mm:ss)']][['Charging Time (hh:mm:ss)','Total Duration (hh:mm:ss)']]

In [70]:
dz['diff']=dz['Charging Time (hh:mm:ss)']-dz['Total Duration (hh:mm:ss)']
dz['diff'].describe()

count                        45
mean     0 days 03:10:06.888888
std      0 days 03:05:07.628100
min             0 days 00:00:01
25%             0 days 00:47:50
50%             0 days 02:12:56
75%             0 days 04:27:55
max             0 days 11:33:30
Name: diff, dtype: object

In [71]:
df[['Energy (kWh)','Fee','Total Duration (hh:mm:ss)']].describe()

        Energy (kWh)            Fee Total Duration (hh:mm:ss)
count  259411.000000  259411.000000                    259411
mean        8.544332       1.097493    0 days 02:29:12.607379
std         7.185497       1.934419    0 days 02:12:45.618782
min         0.010000       0.000000           0 days 00:01:00
25%         3.784000       0.000000           0 days 01:10:15
50%         6.868920       0.000000           0 days 02:05:21
75%        11.458754       1.640000    0 days 03:05:24.500000
max        97.360000      84.560000           4 days 18:32:21

In [72]:
df.shape

(259411, 33)

In [75]:
df = df.drop(df[df['Charging Time (hh:mm:ss)']>df['Total Duration (hh:mm:ss)']].index)

In [76]:
df.shape

(259366, 33)

In [77]:
df.isnull().sum()

Station Name                           0
MAC Address                            0
Org Name                               0
Start Date                             0
Start Time Zone                        0
End Date                               0
End Time Zone                          0
Transaction Date (Pacific Time)      209
Total Duration (hh:mm:ss)              0
Charging Time (hh:mm:ss)               0
Energy (kWh)                           0
GHG Savings (kg)                       0
Gasoline Savings (gallons)             0
Port Type                              9
Port Number                            0
Plug Type                              0
EVSE ID                            78922
Address 1                              0
City                                   0
State/Province                         0
Postal Code                            0
Country                                0
Latitude                               0
Longitude                              0
Currency                            1786
Fee                                    0
Ended By                             247
Plug In Event Id                       0
Driver Postal Code                  8399
User ID                             7674
County                             84639
System S/N                         78922
Model Number                       78922
dtype: int64

In [78]:
df.info()

<class 'pandas.DataFrame'>
Index: 259366 entries, 0 to 259414
Data columns (total 33 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Station Name                     259366 non-null  str
 1   MAC Address                      259366 non-null  str
 2   Org Name                         259366 non-null  str
 3   Start Date                       259366 non-null  datetime64[us]
 4   Start Time Zone                  259366 non-null  str
 5   End Date                         259366 non-null  datetime64[us]
 6   End Time Zone                    259366 non-null  str
 7   Transaction Date (Pacific Time)  259157 non-null  datetime64[us]
 8   Total Duration (hh:mm:ss)        259366 non-null  timedelta64[us]
 9   Charging Time (hh:mm:ss)         259366 non-null  timedelta64[us]
 10  Energy (kWh)                     259366 non-null  float64
 11  GHG Savings (kg)                 259366 non-null  float64
 12  Gasoline Savings (gallons)       259366 non-null  float64
 13  Port Type                        259357 non-null  str
 14  Port Number                      259366 non-null  int64
 15  Plug Type                        259366 non-null  str
 16  EVSE ID                          180444 non-null  float64
 17  Address 1                        259366 non-null  str
 18  City                             259366 non-null  str
 19  State/Province                   259366 non-null  str
 20  Postal Code                      259366 non-null  int64
 21  Country                          259366 non-null  str
 22  Latitude                         259366 non-null  float64
 23  Longitude                        259366 non-null  float64
 24  Currency                         257580 non-null  str
 25  Fee                              259366 non-null  float64
 26  Ended By                         259119 non-null  str
 27  Plug In Event Id                 259366 non-null  int64
 28  Driver Postal Code               250967 non-null  float64
 29  User ID                          251692 non-null  object
 30  County                           174727 non-null  str
 31  System S/N                       180444 non-null  float64
 32  Model Number                     180444 non-null  str
dtypes: datetime64[us](3), float64(9), int64(3), object(1), str(15), timedelta64[us](2)
memory usage: 108.8+ MB

In [79]:
df['Currency']

0         USD
1         USD
2         USD
3         USD
4         USD
         ...
259410    USD
259411    USD
259412    USD
259413    USD
259414    USD
Name: Currency, Length: 259366, dtype: str

In [80]:
df[df.duplicated()]

Empty DataFrame
Columns: [Station Name, MAC Address, Org Name, Start Date, Start Time Zone, End Date, End Time Zone, Transaction Date (Pacific Time), Total Duration (hh:mm:ss), Charging Time (hh:mm:ss), Energy (kWh), GHG Savings (kg), Gasoline Savings (gallons), Port Type, Port Number, Plug Type, EVSE ID, Address 1, City, State/Province, Postal Code, Country, Latitude, Longitude, Currency, Fee, Ended By, Plug In Event Id, Driver Postal Code, User ID, County, System S/N, Model Number]
Index: []

[0 rows x 33 columns]

In [82]:
df.to_csv(r"C:\Users\loneo\OneDrive\Documents\ev-charging-demand-segmentation\data\processed\ev_charging_cleaned.csv",index=False)

In [101]:
df.info()

<class 'pandas.DataFrame'>
Index: 259366 entries, 0 to 259414
Data columns (total 33 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Station Name                     259366 non-null  str
 1   MAC Address                      259366 non-null  str
 2   Org Name                         259366 non-null  str
 3   Start Date                       259366 non-null  datetime64[us]
 4   Start Time Zone                  259366 non-null  str
 5   End Date                         259366 non-null  datetime64[us]
 6   End Time Zone                    259366 non-null  str
 7   Transaction Date (Pacific Time)  259157 non-null  datetime64[us]
 8   Total Duration (hh:mm:ss)        259366 non-null  timedelta64[us]
 9   Charging Time (hh:mm:ss)         259366 non-null  timedelta64[us]
 10  Energy (kWh)                     259366 non-null  float64
 11  GHG Savings (kg)                 259366 non-null  float64
 12  Gasoline Savings (gallons)       259366 non-null  float64
 13  Port Type                        259357 non-null  str
 14  Port Number                      259366 non-null  int64
 15  Plug Type                        259366 non-null  str
 16  EVSE ID                          180444 non-null  float64
 17  Address 1                        259366 non-null  str
 18  City                             259366 non-null  str
 19  State/Province                   259366 non-null  str
 20  Postal Code                      259366 non-null  int64
 21  Country                          259366 non-null  str
 22  Latitude                         259366 non-null  float64
 23  Longitude                        259366 non-null  float64
 24  Currency                         257580 non-null  str
 25  Fee                              259366 non-null  float64
 26  Ended By                         259119 non-null  str
 27  Plug In Event Id                 259366 non-null  int64
 28  Driver Postal Code               250967 non-null  float64
 29  User ID                          251692 non-null  object
 30  County                           174727 non-null  str
 31  System S/N                       180444 non-null  float64
 32  Model Number                     180444 non-null  str
dtypes: datetime64[us](3), float64(9), int64(3), object(1), str(15), timedelta64[us](2)
memory usage: 108.8+ MB